In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.3.2'

In [5]:
df = pd.read_csv("../data/car_fuel_efficiency.csv")

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [10]:
row_count = len(df)
row_count

9704

In [12]:
df["fuel_type"].nunique()

2

In [14]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [20]:
df[df["origin"] == "Asia"].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [21]:
df["horsepower"].mean()

np.float64(149.65729212983547)

In [39]:
most_frequent_value = df["horsepower"].mode()[0]
most_frequent_value

np.float64(152.0)

In [40]:
df["horsepower"] = df["horsepower"].fillna(most_frequent_value)

In [41]:
df["horsepower"].mean()

np.float64(149.82821516900248)

In [43]:
df_asia = df[df["origin"] == "Asia"]

In [47]:
df_asia = df_asia[["vehicle_weight", "model_year"]].head(n=7)

In [49]:
X = df_asia.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [65]:
X_tr = X.T
X_tr

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [63]:
XTX = X_tr.dot(X)
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [67]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [68]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [73]:
w = (XTX_inv.dot(X_tr)).dot(y)
w

array([0.01386421, 0.5049067 ])

In [74]:
w.sum()

np.float64(0.5187709081074001)