#### Vector Operations

In [1]:
import numpy as np

In [7]:
u = np.array([1, 2, 3, 4, 5])
v = np.array([1, 3, 5, 7, 9])

In [8]:
u + v

array([ 2,  5,  8, 11, 14])

#### Vector-vector multiplication

In [9]:
def vtv_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [10]:
vtv_multiplication(u, v)

np.float64(95.0)

In [11]:
u.dot(v)

np.int64(95)

#### Matrix-vector multiplication

In [12]:
U = np.array([[2, 4, 6, 8, 10], [1, 2, 3, 4, 5], [1, 3, 5, 7, 9]])

In [15]:
def mtv_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    rows = U.shape[0]
    result = np.zeros(rows)
    for i in range(rows):
        result[i] = vtv_multiplication(U[i], v)
    return result

In [16]:
mtv_multiplication(U, v)

array([190.,  95., 165.])

In [17]:
U.dot(v)

array([190,  95, 165])

#### Matrix-matrix multiplication

In [40]:
V = np.random.rand(5, 3)
V

array([[0.32385586, 0.81802378, 0.73143924],
       [0.34223697, 0.79836494, 0.34174623],
       [0.4976365 , 0.02269524, 0.48338383],
       [0.6543981 , 0.26352   , 0.97393952],
       [0.88973208, 0.67943172, 0.46683459]])

In [20]:
def mtm_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    rows = U.shape[0]
    cols = V.shape[1]
    result = np.zeros((rows, cols))
    for i in range(cols):
        vi = V[:, i]
        Uvi = mtv_multiplication(U, vi)
        result[:, i] = Uvi
    return result

In [41]:
mtm_multiplication(U, V)

array([[19.13498412, 13.86815598, 18.19002839],
       [ 9.56749206,  6.93407799,  9.09501419],
       [16.42712462, 11.2861203 , 15.19268498]])

In [42]:
U.dot(V)

array([[19.13498412, 13.86815598, 18.19002839],
       [ 9.56749206,  6.93407799,  9.09501419],
       [16.42712462, 11.2861203 , 15.19268498]])

#### Identity Matrix

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Matrix Inverse

In [48]:
Vs = V[[0, 1, 2]] # matrix square
Vs

array([[0.32385586, 0.81802378, 0.73143924],
       [0.34223697, 0.79836494, 0.34174623],
       [0.4976365 , 0.02269524, 0.48338383]])

In [51]:
Vs_inv = np.linalg.inv(Vs) # inversed matrix Vs
Vs_inv

array([[-2.38351969,  2.38767073,  1.91860446],
       [-0.02920509,  1.30750577, -0.88019785],
       [ 2.45516943, -2.51946006,  0.13490044]])

In [52]:
I = Vs_inv.dot(Vs) # identity matrix
I

array([[ 1.00000000e+00, -2.49800181e-16,  1.11022302e-16],
       [ 5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [ 5.55111512e-17,  1.28369537e-16,  1.00000000e+00]])