### Intro to Numpy

#### Creating arrays

In [4]:
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
arr = np.array([1, 2, 3, 4, 5])

In [9]:
arr[2]

np.int64(3)

In [10]:
arr[3] = 5
arr

array([1, 2, 3, 5, 5])

In [11]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [12]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### Multi-dimensional array

In [13]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
n = np.array([[1, 2, 3], [4, 5, 6]])

In [17]:
n[0][1]

np.int64(2)

In [18]:
n[0][1] = 5
n

array([[1, 5, 3],
       [4, 5, 6]])

In [19]:
n[1]

array([4, 5, 6])

In [21]:
n[1] = [3, 3, 3]
n

array([[1, 5, 3],
       [3, 3, 3]])

In [22]:
n[:, 1]

array([5, 3])

In [25]:
n[:, 1] = [1, 7]
n

array([[1, 1, 3],
       [3, 7, 3]])

#### Randomly generated array

In [26]:
np.random.seed(5)

In [27]:
np.random.rand(5, 3)

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

In [28]:
np.random.randn(5, 3)

array([[-0.60529785, -1.59441507,  0.91187364],
       [-1.44384155,  1.82444017,  1.45762512],
       [-0.91025815, -0.99001894, -0.81754812],
       [-1.16827947, -0.21077965, -0.22429966],
       [ 0.65122845, -0.96276198,  2.23874294]])

In [29]:
np.random.randint(low=0, high=100, size=(5, 3))

array([[ 3, 91, 78],
       [27, 29, 33],
       [89, 85,  7],
       [16, 94, 14],
       [90, 31,  9]])

#### Element-wise operations

In [41]:
a = np.arange(5) + 11
a

array([11, 12, 13, 14, 15])

In [34]:
b = (10 + (a * 2)) / 0.5
b

array([20., 24., 28., 32., 36.])

In [32]:
a + b

array([20., 25., 30., 35., 40.])

#### Comparison operations

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [36]:
a > b

array([False, False, False, False, False])

In [44]:
a[b % a == 0]

array([12])

#### Summarizing operations

In [45]:
a.min()

np.int64(11)

In [46]:
a.max()

np.int64(15)

In [47]:
a.sum()

np.int64(65)

In [48]:
a.mean()

np.float64(13.0)

In [49]:
a.std()

np.float64(1.4142135623730951)